# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naQoUGIKRiEpHR2GcqhCHr-mPJsUXOMf
"""

# scripts/preprocessing.py

import yfinance as yf
import pandas as pd
import numpy as np

#NVIDIA hitsorical Prices (yahoo finance)
def load_data_yfinance(ticker: str, period: str = "10y") -> pd.DataFrame:
    df = yf.download(ticker, period=period)[['Close']].copy()
    df.dropna(inplace=True)
    df.rename(columns={'Close': 'Price'}, inplace=True)
    return df
#Load CSV data of nvidia
def load_data_csv(path: str, price_col: str = 'Close') -> pd.DataFrame:

    df = pd.read_csv(path, parse_dates=True, index_col=0)
    df = df[[price_col]].dropna().rename(columns={price_col: 'Price'})
    return df

#Log Transformed Price data of NVIDIA
def add_log_price(df: pd.DataFrame, price_col: str = 'Price') -> pd.DataFrame:
    df = df.copy()
    df['LogPrice'] = np.log(df[price_col])
    return df